### PR TITLE
Introduce getSignaturesForAsset function

### PR DESCRIPTION
**Pull request by kiv1**
### Features:

- Add support for `getSignaturesForAsset`

### CODE REVIEW

**Review by Juanito87 — APPROVED** [review]
LGTM

**Comment by NicolasPennie** [comment]
This should be a merge from the Helius repo so that the original author is credited for their work (@nikhil-helius).

**Comment by kiv1** [comment]
@NicolasPennie I apologize for the not crediting the developer. Initially, I attempted to fork from Helius repository and merge what Metaplex had locally. However, the `cl_audit` table uses a different schema than the one currently in use here. Consequently, I decided to integrate Helius `getSignaturesForAsset` into the current Metaplex repository, working under the assumption that this will require minimal database changes for vendors already running the latest version of this repository.

**Comment by NicolasPennie** [comment]
> @NicolasPennie I apologize for the not crediting the developer. Initially, I attempted to fork from Helius repository and merge what Metaplex had locally. However, the `cl_audit` table uses a different schema than the one currently in use here. Consequently, I decided to integrate Helius `getSignaturesForAsset` into the current Metaplex repository, working under the assumption that this will require minimal database changes for vendors already running the latest version of this repository.


Thats ok, I totally understand. The merges are very tricky. @nikhil-helius can make a PR today and we can get that in ASAP.

**Comment by brianlong** [comment]
Thanks @NicolasPennie & @nikhil-helius !

**Comment by nikhil-helius** [comment]
Created https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/pull/137

**Comment by febo** [comment]
@nikhil-helius Should we close this PR in favour of #137 ?

**Comment by kiv1** [comment]
Both PR looks identical so no issues.

**Comment by febo** [comment]
Closed in favour of #137

**Pull request closed without merging**
