### PR TITLE
fix: make delegate string (#73)

### PR DESCRIPTION
**Pull request by linuskendall**
upstreaming pr from helius labs to ensure compatible apis: 

https://github.com/helius-labs/digital-asset-rpc-infrastructure/pull/73

### CODE REVIEW

**Comment by linuskendall** [comment]
@tahsintunan pushing this upstream so that not everyone has slightly incompatible apis.

**Comment by tahsintunan** [comment]
Sg

**Comment by danenbm** [comment]
On hold as we expect this PR to be merged as part of a creator/data hash fix PR.

**Review by danenbm — APPROVED** [review]
LGTM

**Pull request merged**
